// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfuttjouopjgasunownl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdXR0am91b3BqZ2FzdW5vd25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTQ5MTksImV4cCI6MjA3NDYzMDkxOX0.catIayrNGWg7SsUHeukcUVchPMdVGNyWUHpRvZnAEHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});